--CAU 36 Tính tổng số lượng của từng sản phẩm bán ra trong tháng 10/2006.
SELECT MASP,SUM(SL) [TONG SO LUONG]
FROM  HOADON A, CTHD B
WHERE A.SOHD=B.SOHD AND MONTH(NGHD)=10 AND YEAR(NGHD)=2006 
GROUP BY MASP 
--CAU 37 Tính doanh thu bán hàng của từng tháng trong năm 2006.
SELECT MONTH(NGHD) THANG,SUM(TRIGIA) [DOANH THU]
FROM  HOADON A, CTHD B
WHERE A.SOHD=B.SOHD AND YEAR(NGHD)=2006 
GROUP BY MONTH(NGHD)
--CAU 38 Tìm hóa đơn có mua ít nhất 4 sản phẩm khác nhau.
SELECT *
FROM  HOADON
WHERE SOHD IN (SELECT SOHD
FROM  CTHD
GROUP BY SOHD
HAVING COUNT(DISTINCT MASP)>=4)
--CAU 39 Tìm hóa đơn có mua 3 sản phẩm do “Viet Nam” sản xuất (3 sản phẩm khác nhau).
SELECT *
FROM  HOADON
WHERE SOHD IN (SELECT SOHD
FROM  CTHD A, SANPHAM B
WHERE A.MASP=B.MASP AND NUOCSX='VIET NAM'
GROUP BY SOHD
HAVING COUNT(DISTINCT A.MASP)=3)
--CAU 40 Tìm khách hàng (MAKH, HOTEN) có số lần mua hàng nhiều nhất.
SELECT *
FROM  KHACHHANG
WHERE MAKH IN (SELECT MAKH
FROM  HOADON
GROUP BY MAKH
HAVING COUNT(SOHD)>=ALL(SELECT  COUNT(SOHD)
FROM  HOADON
GROUP BY MAKH))
--CAU 41 Tháng mấy trong năm 2006, doanh số bán hàng cao nhất ?
SELECT MONTH(NGHD) THANG
FROM  HOADON
WHERE YEAR(NGHD)=2006
GROUP BY MONTH(NGHD)
HAVING SUM(TRIGIA)>=ALL(SELECT SUM(TRIGIA)
FROM  HOADON
WHERE YEAR(NGHD)=2006
GROUP BY MONTH(NGHD))
--CAU 42 Tìm sản phẩm (MASP, TENSP) có tổng số lượng bán ra thấp nhất trong năm 2006.
SELECT B.MASP, TENSP
FROM  SANPHAM A,CTHD B, HOADON C
WHERE A.MASP=B.MASP AND B.SOHD=C.SOHD AND YEAR(NGHD)=2006
GROUP BY B.MASP,TENSP
HAVING SUM(SL)>=ALL(SELECT  SUM(SL)
FROM  CTHD A, HOADON B
WHERE A.SOHD=B.SOHD AND YEAR(NGHD)=2006
GROUP BY MASP)
--CAU 43 *Mỗi nước sản xuất, tìm sản phẩm (MASP,TENSP) có giá bán cao nhất.
SELECT NUOCSX,MASP, TENSP
FROM  SANPHAM A
WHERE GIA=(SELECT MAX(GIA)
FROM  SANPHAM B
WHERE A.NUOCSX=B.NUOCSX)
GROUP BY NUOCSX,MASP,TENSP
--CAU 44 Tìm nước sản xuất sản xuất ít nhất 3 sản phẩm có giá bán khác nhau.
SELECT NUOCSX
FROM  SANPHAM
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA)>=3
--CAU 45 *Trong 10 khách hàng có doanh số cao nhất, tìm khách hàng có số lần mua hàng nhiều nhất.
SELECT *
FROM  KHACHHANG
WHERE MAKH IN (SELECT A.MAKH
FROM  HOADON A, KHACHHANG B
WHERE A.MAKH=B.MAKH AND
DOANHSO IN (SELECT TOP 10 DOANHSO
FROM  KHACHHANG
ORDER BY DOANHSO DESC) 
GROUP BY A.MAKH
HAVING COUNT(SOHD)>=ALL(SELECT  COUNT(SOHD)
FROM  HOADON A, KHACHHANG B
WHERE A.MAKH=B.MAKH AND
DOANHSO IN (SELECT TOP 10 DOANHSO
FROM  KHACHHANG
ORDER BY DOANHSO DESC)  
GROUP BY A.MAKH))
