---bài1---
SELECT THOIGIAN+CAST(PHANCONG.THOIGIAN AS decimal(6,2))
  FROM PHANCONG
  GO
  SELECT THOIGIAN + CONVERT(decimal(6,2),101)
  FROM PHANCONG

 ---

  SELECT THOIGIAN+CAST(PHANCONG.THOIGIAN AS VARCHAR)
  FROM PHANCONG
  GO
  SELECT THOIGIAN + CONVERT(VARCHAR,101)
  FROM PHANCONG
  ----
  SELECT TENPHG, CAST(AVG(LUONG) as decimal(10,2)) AS 'Lương trung bình' from NHANVIEN
INNER JOIN PHONGBAN ON NHANVIEN.PHG=PHONGBAN.MAPHG
GROUP BY TENPHG
  ----
SELECT TENPHG, LEFT(CAST(AVG(LUONG) as varchar(10)), 3)+','
+REPLACE(CAST(AVG(LUONG) as varchar(10)), LEFT(CAST(AVG(LUONG) as varchar(10)), 3), ',' )
AS 'Lương trung bình' from NHANVIEN
INNER JOIN PHONGBAN ON NHANVIEN.PHG=PHONGBAN.MAPHG
GROUP BY TENPHG
---bài2---
SELECT TENDEAN, CEILING(CAST(SUM(THOIGIAN) AS decimal(5,2))) AS 'tổng số giờ làm việc' FROM CONGVIEC
INNER JOIN DEAN ON CONGVIEC.MADA=DEAN.MADA
INNER JOIN PHANCONG ON CONGVIEC.MADA=PHANCONG.MADA
GROUP BY TENDEAN
---
 SELECT TENDEAN, FLOOR(CAST(SUM(THOIGIAN) AS decimal(5,2))) AS 'tổng số giờ làm việc' FROM CONGVIEC
INNER JOIN DEAN ON CONGVIEC.MADA=DEAN.MADA
INNER JOIN PHANCONG ON CONGVIEC.MADA=PHANCONG.MADA
GROUP BY TENDEAN
---
SELECT TENDEAN, ROUND(CAST(SUM(THOIGIAN) AS decimal(5,2)), 2) AS 'tổng số giờ làm việc' FROM CONGVIEC
INNER JOIN DEAN ON CONGVIEC.MADA=DEAN.MADA
INNER JOIN PHANCONG ON CONGVIEC.MADA=PHANCONG.MADA
GROUP BY TENDEAN
---
SELECT LUONG, (HONV+' '+TENLOT+' '+TENNV+' ') AS 'Họ tên NV có mức lương trung bình' FROM NHANVIEN
WHERE LUONG>
(SELECT ROUND(AVG(LUONG), 2) FROM NHANVIEN, PHONGBAN
WHERE PHG=MAPHG AND TENPHG=N'Nghiên cứu')
---bài3---
SELECT UPPER(HONV) AS 'Nhân viên có trên 2 thân nhân', TENLOT, TENNV, DCHI
FROM NHANVIEN, THANNHAN
WHERE NHANVIEN.MANV=THANNHAN.MA_NVIEN
GROUP BY UPPER(HONV), TENLOT, TENNV, DCHI
HAVING COUNT(THANNHAN.MA_NVIEN) > 2
---
SELECT UPPER(HONV) AS 'TENNV', LOWER(TENLOT) AS 'TENLOT', TENNV, DCHI
FROM NHANVIEN, THANNHAN
WHERE NHANVIEN.MANV=THANNHAN.MA_NVIEN
GROUP BY UPPER(HONV), LOWER(TENLOT), TENNV, DCHI
HAVING COUNT(THANNHAN.MA_NVIEN) > 2
---
SELECT UPPER(HONV) AS 'TENNV', LOWER(TENLOT) AS 'TENLOT', 
LOWER(LEFT(TENNV, 1))+UPPER(SUBSTRING(TENNV, 2, 1))+LOWER(SUBSTRING(TENNV, 3, LEN(TENNV))), DCHI
FROM NHANVIEN, THANNHAN
WHERE NHANVIEN.MANV=THANNHAN.MA_NVIEN
GROUP BY UPPER(HONV), LOWER(TENLOT), 
LOWER(LEFT(TENNV, 1))+UPPER(SUBSTRING(TENNV, 2, 1))+LOWER(SUBSTRING(TENNV, 3, LEN(TENNV))), DCHI
HAVING COUNT(THANNHAN.MA_NVIEN) > 2
---
SELECT UPPER(HONV) AS 'TENNV', LOWER(TENLOT) AS 'TENLOT', 
LOWER(LEFT(TENNV, 1))+UPPER(SUBSTRING(TENNV, 2, 1))+LOWER(SUBSTRING(TENNV, 3, LEN(TENNV))), 
SUBSTRING(DCHI, CHARINDEX(' ', DCHI)+1, CHARINDEX(',', DCHI) - CHARINDEX(' ', DCHI)-1)
FROM NHANVIEN, THANNHAN
WHERE NHANVIEN.MANV=THANNHAN.MA_NVIEN
GROUP BY UPPER(HONV), LOWER(TENLOT), 
LOWER(LEFT(TENNV, 1))+UPPER(SUBSTRING(TENNV, 2, 1))+LOWER(SUBSTRING(TENNV, 3, LEN(TENNV))), 
SUBSTRING(DCHI, CHARINDEX(' ', DCHI)+1, CHARINDEX(',', DCHI) - CHARINDEX(' ', DCHI)-1)
HAVING COUNT(THANNHAN.MA_NVIEN) > 2
---
DECLARE @THONGKE TABLE (MAP INT, MANVTP INT, TK INT)
INSERT INTO @THONGKE
SELECT PHG, MA_NQL, COUNT(MANV) FROM NHANVIEN GROUP BY PHG, MA_NQL
DECLARE @MAX INT
SELECT @MAX = MAX(TK) FROM @THONGKE
SELECT TENPHG, HONV+' '+TENLOT+' '+TENNV AS 'Họ tên NV', HONV+' '+TENLOT+' Fpoly' AS 'Họ tên FPOLY' FROM PHONGBAN
A INNER JOIN (SELECT *FROM @THONGKE WHERE TK=@MAX) B ON A.MAPHG = B.MAP
INNER JOIN NHANVIEN C ON C.MANV = B.MANVTP
---bài 4---
SELECT * FROM NHANVIEN
WHERE YEAR(NGSINH)
BETWEEN 1960 AND 1965
---
SELECT YEAR(GETDATE())-YEAR(NGSINH) AS 'Tuổi', TENNV FROM NHANVIEN
---
SELECT DATENAME(WEEKDAY, NGSINH) AS 'Thứ', TENNV FROM NHANVIEN
---
SELECT TRPHG, HONV+' '+TENLOT+' '+TENNV AS 'Họ tên TP', CONVERT(VARCHAR, NG_NHANCHUC, 105) AS 'Ngày nhận chức', SL AS 'SLNV'
FROM PHONGBAN
A INNER JOIN (SELECT PHG, COUNT(MANV) AS SL FROM NHANVIEN GROUP BY PHG) B ON A.MAPHG=B.PHG
INNER JOIN NHANVIEN C ON A.TRPHG=C.MANV